name: AI Issue and Discussion Labeler

on:
  issues:
    types: [opened, edited, reopened]
  discussion:
    types: [created, edited]

permissions:
  issues: write
  discussions: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: AI Issue and Discussion Labeler
        uses: Disdjj/labeler@v1.0.4 # Replace with your repo and a specific version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.AI_API_KEY }}
          base-url: ${{ secrets.AI_BASE_URL }}
          model: 'gpt-5-mini'
          # prompt: 'Your custom prompt here. Use {issue_title}, {issue_body}, and {existing_labels}.'