name: Generate Weekly Report

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每周一上午8点 (UTC时间0点，北京时间8点)
    - cron: '0 0 * * 1'

permissions:
  contents: write
  issues: read
  pull-requests: read
  discussions: read

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Python dependencies
      run: |
        pip install PyGithub
        
    - name: Generate weekly report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/generate_weekly_report.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generate weekly report $(date +'%Y%m%d')"
          git push
        fi
